language: erlang
branches:
    only:
        - master
        - release_2.0
        - otp_18_plus
matrix:
    include:
        - otp_release: 23.0
        - otp_release: 22.3
        - otp_release: 21.3
        - otp_release: 20.3
        - otp_release: 19.3
        - otp_release: 19.3
          env: XPROF_ERL_HIST=true
        - otp_release: 18.3
          dist: trusty
          env: COWBOY_VERSION=1.1.2
cache:
    directories:
        - $HOME/.cache/rebar3
        - apps/xprof_gui/priv/node_modules
install:
    - rebar3 --version
    - rebar3 deps
    - nvm install 8.11.1 && nvm use 8.11.1
    - make bootstrap_front_end
script:
    - make test
    - make test_front_end
    - if [ $TRAVIS_OTP_RELEASE = "21.3" ]; then make doc dialyzer; fi
    - if [ $TRAVIS_OTP_RELEASE = "18.3" ]; then make dialyzer; fi   # run dialyzer with cowboy 1.x too
after_success:
    - ./rebar3 cover
    - if [ $TRAVIS_OTP_RELEASE = "21.3" ]; then ./rebar3 coveralls send; fi
